### ISSUE TITLE
♻ Reduce, reuse, recycle in Singapore

### ISSUE THREAD

**Issue by JennieJi** [Shopee/shopee-react-knowledgeable#110]
Speaker
---

@JennieJi 

Intro
---

Base on #105 , share my experiences of how I reduce, reuse, recycle when living in Singapore.

Ready by
---

End of June

**Comment by wgao19** [comment]
Thanks for the proposal! Please let us know when you're ready and we'll slot you in. Expecting early July.

**Comment by JennieJi** [comment]
sure

**Comment by JennieJi** [comment]
@wgao19 slides drafted, may have dry run next or next next week?

**Comment by wgao19** [comment]
Hey @JennieJi do you know roughly how long is your talk?

**Comment by JennieJi** [comment]
Not yet, will update you later

**Comment by wgao19** [comment]
presumably rescheduled to aug 23 due to, life

**Comment by wgao19** [comment]
Hey @JennieJi scheduled this in for RK40 on Aug 23 #128

**Comment by JennieJi** [comment]
noted, thx

**Comment by KenLSM** [comment]
@JennieJi Thanks for your sharing your tips and learnings today! Could you also upload your slides so that I can close this issue?

**Comment by JennieJi** [comment]
@KenLSM here: https://docs.google.com/presentation/d/18vmiEPVLef3KLFLJUSunJiuuBqdaloeJ9dMp5H7Hs3I/edit?usp=sharing
