### ISSUE TITLE
🌏 Yet another react-native for web

### ISSUE THREAD

**Issue by nutstick** [Shopee/shopee-react-knowledgeable#123]
Speaker
---
Nuttapat Kirawittaya

Intro
---

[react-native-dom](https://github.com/vincentriemer/react-native-dom). An experimental, comprehensive port of React Native to the web. And attempt to integrate in shopee.

**Edit by @wgao19**: Removed Shopee related screenshot.

---
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by:
- Needs dry run:

**Comment by wgao19** [comment]
lol, I love this title, awesome man.

**Comment by wgao19** [comment]
[slides](https://docs.google.com/presentation/d/1apHeBR_BnG7kkTMARYuaC4LAB7oEm4HT4Vu4N-Ioz58/edit#slide=id.g5d3fef0094_0_0)
