### ISSUE TITLE
🧐 Interesting things I learned about layout

### ISSUE THREAD

**Issue by huijing** [Shopee/shopee-react-knowledgeable#130]
Speaker
---
@huijing

Intro
---
Hi,

My name is Hui Jing. I am the person who always come Shopee disturb you all. 

I'd like to talk about interesting things I learned about layout and CSS on 16 Aug.

Here's a little more background and motivation about the talk:

Some people might find this weird, but I actually like CSS, and build layouts for fun. So this is just a bunch of things I picked up along the way.

As you can see above, I have a point to make. Please let me in thanks.

- Estimated duration:  🧙🏻‍♂️ <30 mins
- Ready by: 16 Aug
- Needs dry run: No

**Comment by wgao19** [comment]
Thanks for the great talk @huijing!
[slides](https://www.chenhuijing.com/slides/62-interesting-layout-css/)
