### ISSUE TITLE
👽 Building Web-Based Audio Player for Obscure Audio Format

### ISSUE THREAD

**Issue by kenrick95** [Shopee/shopee-react-knowledgeable#131]
## Speaker
Kenrick

## Details

Recently, I randomly submitted [this talk proposal](https://www.papercall.io/speakers/52981/speaker_talks/148391-building-web-based-audio-player-for-obscure-audio-format) to [Geekcamp 2019](https://geekcamp.sg/) and unexpectedly they accepted it 😱😱😱. Now I need to start really making the slides (since the event will happen in October) and I hope I could use React Knowledgable to practice giving out my talk.

- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: mid September 2019
- Needs dry run: Yes

**Comment by wgao19** [comment]
Amazing! Onz!!!

**Comment by wgao19** [comment]
scheduling this to be delivered on Sept 20 and dry run Sept 13 :))))

**Comment by JennieJi** [comment]
congrats!!! looking forward to it😆

Best Regards,
Jennie Ji

________________________________

**Comment by wgao19** [comment]
notes from dry run :)))

- can include use case first? to make it more relevant to more people
- find an iconic game music and "demysify" how come it's looping
- include reference to the name "Nikku"

(sorry about the lateness, forgot to hit "comment" by the end of our dry run)

**Comment by wgao19** [comment]
will update slides after kenrick's talk at geekcamp :))))
