### ISSUE TITLE
👾 EQ vs IQ - The 2 stories of success

### ISSUE THREAD

**Issue by thientran1707** [Shopee/shopee-react-knowledgeable#141]
speaker
@thientran1707

intro
People say a lot about importance of IQ in life. However, EQ is also important.
As Shopee has Ronaldo as the new ambassador, I will use Ronaldo and Messi as the example of IQ vs EQ and how we can achieve success in life differently

resources
---

Scheduling
---
- Estimated duration: ⚡️ 7 mins 
- Ready by:
- Needs dry run:

**Comment by wgao19** [comment]
Hi @thientran1707 will u be up for this week?
