### ISSUE TITLE
 👀 Online shopping as a blind person

### ISSUE THREAD

**Issue by gejimayu** [Shopee/shopee-react-knowledgeable#142]
speaker
---
@gejimayu

intro
---
How do visually impaired people shop online ? let's talk briefly about the basic of accessibility and do a quick demo on Shopee.

resources
---
slides: https://docs.google.com/presentation/d/1Xj1Iu2SJyns3kCdd9jT4s-rfUOwlhk2KAwttHA0EFZQ/edit?usp=sharing

Scheduling
---
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by:
- Needs dry run:

**Comment by wgao19** [comment]
Thank you for speaking! 
Will Oct 4 be OK for you? Meanwhile, if you'd like to dry run your talk once before the actual talk, Sept 27 is open.

**Comment by wgao19** [comment]
Dry run is aimed at helping ourselves rehearse the talk, normally me and Ken will be there, anyone interested in the topic may join, and you may invite those who you think might be able to help your preparation. They happen the hour before RK (1700 - 1800), but for it to be useful, better take the slot a week in advance.

**Comment by gejimayu** [comment]
Hi i don't think you want to hear me talk twice hahah.

Thus i hope i will be fine without it.

**Comment by wgao19** [comment]
@gejimayu cool, sure i'll go with the surprises, good luck for your talk!

**Comment by wgao19** [comment]
Hi @gejimayu I did not find a chance to let you know in person that I think your sharing today was absolutely gorgeous! I really love your sense of humor and I regret not knowing more about you earlier!

**Comment by wgao19** [comment]
Oh and if you don’t mind could you have a writeup for the outline of your talk with a few links to some resources for people interested in the topic?

**Comment by gejimayu** [comment]
Really, i thought i was an epic failure hahah. 
Thanks btw, means a lot.
Yeah sure no prob, will write back here.

**Comment by gejimayu** [comment]
Hi @wgao19 , here's the summary, hopefully this is enough

1. What
Accessibility is the practice of making your websites usable by as many people as possible. 
2. Why
   - There are 39 millions of blind people all over the world. Comparable to IE users (120 millions)
   - Increase usability and SEO of our product
   - Required by law on some country, could get sued if not accessible
3. How to use Voice Over on mac 
System preference -> Accessibility -> Voice Over training
4. How Screen Reader Works (Accessibility Tree)
http://wicg.github.io/aom/explainer.html
5. Practical things:
   - Always use alt text for image
   - Utilize `tabindex` 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
   - Use proper heading in order (from h1 .. h6) and HTML sectioning elements (header, nav, main, footer, etc.) 
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html
   - Provide voice captcha if you have image captcha
   - Use ARIA property to give semantics especially for custom elements 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets
   - Use `role="alert"` for popup/modals/message that needs immediate attention
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

**Comment by wgao19** [comment]
cool, thank u @gejimayu !
