### ISSUE TITLE
👾 Functional programming practices in JS

### ISSUE THREAD

**Issue by t1ger-0527** [Shopee/shopee-react-knowledgeable#143]
speaker
---
@t1ger-0527 

intro
---
Will cover these FP practices in JS (from more known to less known)
- underscore/lodash
- [Ramda](https://ramdajs.com/)
- [Fantasy Land](https://github.com/fantasyland/fantasy-land/tree/v4.0.1) and [Sanctuary](https://github.com/sanctuary-js/sanctuary)
- Review [Dan's blogpost](https://overreacted.io/algebraic-effects-for-the-rest-of-us/) (Since we mentioned the word Algebraic). 

Focus:
- FP Concepts (more on `why` rather than `how`).
- Things we, as Web Developers, can borrow and learn (and maybe use).

resources
---
My own explorations and insights.

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: Oct 4th (Friday).
- Needs dry run: Yes please!

**Comment by wgao19** [comment]
sure, i'll be out of town on sept 27, can we put u on oct 4 for dry run and the week after for actual talk?

**Comment by t1ger-0527** [comment]
@wgao19 Cool! Thanks!

**Comment by wgao19** [comment]
- history part can be shortened (i think)
- need a proper intro to FP
- plz add a bunch of FP jokes :)))))))
- there was a currey typo
- i feel the content has two goals
  - takehome "point free"
  - how the JS world (JS libraries) picks them up -> which is a great perspective, nice bridge to our own use cases too

- [anjana's fp talk](https://www.youtube.com/watch?v=1QY7P_yXc_M)
