### ISSUE TITLE
👩🏻‍💻 Panelist Discussion: Thoughts on Career as a Developer 👨🏻‍💻

### ISSUE THREAD

**Issue by wgao19** [Shopee/shopee-react-knowledgeable#146]
A special event for our anniversary episode!!

when?
---
- **Oct 11, 2019**
- RK 47, #145

intro
---
We’re planning an RK anniversary event and we’d like to organize a panelist discussion on thoughts on our careers as developers. 

Other than some of our very senior team members, we'd also like to take this chance to highlight some of our peer developers who seem to be happy with what they're doing, and who seem to be working on interesting things.

wanna <kbd>A</kbd> questions at someone?
---
We'll use this issue as a curator for questions. Please comment below that includes:
- questions you'd like to ask
- who you'd like to hear from, there can be multiple people

**Comment by tanhauhau** [comment]
To van,
How did you manage to do masters, CSS drawings and karate in the same time?
What's next after CSS drawings?

**Comment by fiennyangeln** [comment]
To all,
Any advice for a newbie like me to navigate through my career later when I graduate?

**Comment by wgao19** [comment]
hey @fiennyangeln would you like to come to this event?

**Comment by gejimayu** [comment]
To Mr. Chenchen Sun,
If you could go back to be a fresh grad, what would you do differently ?

**Comment by t1ger-0527** [comment]
To master. Tan hau hau:

Can you share with us some interesting facts (or fundamentals) about building cli softwares?

**Comment by fiennyangeln** [comment]
I'd love to! But I will be overseas on that date 😿

**Comment by tanhauhau** [comment]
To all,

- Why did you decide to be a web frontend developer?
- What is your proudest achievement in shopee?
- What is your toughest decision in shopee?
- What is your greatest lesson in shopee?
- Any regrets made in Shopee

To chenchen & benze / all
- Any technical decision made in shopee that you would wish to do it differently?

**Comment by gejimayu** [comment]
To Mister Jinjiang.

How did you get started to contribute to open source

**Comment by wgao19** [comment]
Event Notes
---
Thank you all for participating in this event! Here are my notes from the discussions. They are biased towards questions I have taken notes for, or I still remember. It's very dependent on what I was doing. If I was hosting I was probably not taking notes and therefore forgetting stuff. 

Characteristics
---
### Kenrick: Good traits to a good developer
- knowledge about computer science
- read the book Clean Code https://www.goodreads.com/book/show/3735293-clean-code
- ask questions, don't wait for others to ask you

### Huijing: Greatest characteristics you see in the best developers you’ve met?
- ability to communicate, "the human side of things"
- keep an open mind
- be humble

Tell us about how you build your knowledge base
---
### Jinjiang's answer
- read from an article that personally agree with to be good sources: 
  + read docs
  + read source code
  + find everything written by the creator
- practices
  + spend a bunch of time in the topic
  + follow up reading, blog posts, subscriptions, etc
  + practice (build demos and stuff)

### Huijing's answer
- there are two types, general knowledge and going deep
- 积少成多 accumulatively you know a lot after years
- consistency

### Chenchen's answer
- GitHub → README → source code → issues
- for beginners (to our team), ask in mattermost channel
- we sometimes share stuff in our mattermost channel too

Chenchen: Growth with Shopee
---
- year 1:
  + first month: fix bugs
  + mainly year 1 - doing features and learning about fe
- year 2: created PC site, started to "mentor" people, had a small fe team
- year 3: decided to get rid of jQuery completely, build mobile web, team grows
- year 4: 
  + biggest challenge is team grew 300%, need to learn how to maintain the team, prefer not to call it "management" but "the human part of it"
  + technically: coded less, understand fe more, take care of performance, how to optimize for actual users not just making lighthouse happy

Questions from the ground
---
### Question for Jinjiang: Tell us about the band 996? Plan to have a band here?
- point is that there is more things beside working hard
- but there's no plan to start a band here
side note: our team is a great source of talent

### Anything to cash our talents?
/ extended discussion with choice of career

### Chenchen
- code alone to earn money is very inefficient
- prefers to do other thing over weekend

### Huijing
- it's a choice, it's easy to earn cash but it's hard to build a career
- chose career because she feels like it

### Wei
- earned a lot of cash by teaching math, created a lot of math majors
- kept doing it for a while because my experience was helpful to the students in that program
- very stressful so eventually decided to focus on main career
- chose front end as main career because i feel like it
