### ISSUE TITLE
🇨🇳 JSConfChina Recap

### ISSUE THREAD

**Issue by wgao19** [Shopee/shopee-react-knowledgeable#150]
speaker
---
@wgao19 

intro
---
I'm actually very curious what's gonna happen in [JSConf China](https://2019.jsconfchina.com/). China is an environment where I started my career as a front end developer and so it's a chance for me to revisit. Some talks look interesting by titles too. It'll also be my first conference trip as a speaker, not sure if I'll have anything to share about that, so, let's see.

resources
---

scheduling
---
- Estimated duration:  🧙🏻‍♂️ 20 mins
- Ready by: #148 
- Needs dry run: no

**Comment by jianhua1982** [comment]
Excellent speaker. 
Where is your ppt link? Not catch it during the meeting.

**Comment by wgao19** [comment]
@jianhua1982 thank you for the kind words! You can find the slides and the resources links here: https://uuei.io/talks/docs/jsconfchina/
