### ISSUE TITLE
⚡️ Short Stories working on Svelte

### ISSUE THREAD

**Issue by tanhauhau** [Shopee/shopee-react-knowledgeable#154]
speaker
---
@tanhauhau 

intro
---
Over the recent #hacktoberfest, I've been contributing into [Svelte](https://github.com/sveltejs/svelte), particularly focused on issues to reduce the generated output size.

Fun fact: I innocently created a [XSS vulnerability](https://github.com/sveltejs/svelte/issues/3813)

resources
---

https://lihautan.com/short-stories-working-on-svelte/

Scheduling
---
- Estimated duration: ⚡️ 10 mins ~ 15mins
- Ready by: 13 Nov
- Needs dry run: 🙅‍♂️

**Comment by wgao19** [comment]
sounds good, looking forward

**Comment by wgao19** [comment]
Any updates for this one? @tanhauhau

**Comment by tanhauhau** [comment]
Polishing up the slides, comfortable to do it this week or next

**Comment by wgao19** [comment]
Do you know how long time you need?

**Comment by wgao19** [comment]
Thank you for the short stories! Unfortunately we cannot publish the video at the moment because of internal content protection. Will share with you the video file early next week.
