### ISSUE TITLE
🎼 It Hertz if I Synth

### ISSUE THREAD

**Issue by Tzyinc** [Shopee/shopee-react-knowledgeable#158]
speaker
---
Tenzy

intro
---
Tenzy sometimes makes sounds on musical instruments but cannot play music. Web Audio API is usually used to play music and stream music, let's take a look at the science behind sounds and make a synthesiser out of the tools available.

resources
---
http://www.windytan.com/2017/11/in-pursuit-of-otamas-tone.html
https://webaudio.github.io/web-audio-api/#waveform-generation
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createPeriodicWave
https://pages.mtu.edu/~suits/NoteFreqCalcs.html

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: 22 nov
- Needs dry run: sure

**Comment by wgao19** [comment]
Hi, so, does that mean you'll dry run next Friday?

**Comment by Tzyinc** [comment]
yup I can dry run this friday

**Comment by wgao19** [comment]
- link to otamaphone  
  https://httpserve.tenzhiyang.com/otamaphone/
