### ISSUE TITLE
🌱 How to make better use of Chrome Devtools 

### ISSUE THREAD

**Issue by heyjiawei** [Shopee/shopee-react-knowledgeable#159]
How to make better use of Chrome Devtools 🐘 

speaker
jiawei

intro
I have been a console logger developer from the start of my computer science journey and I agree it is hands down the best debugging tool. I would even go as far as to say it may be the only debugging tool you need, if you just need to debug logic. But the web projects I have worked on in companies showed that logic is only a fraction of web applications. So I would like to share some devtools tips and tricks I learnt in the past year. As devtools is a huge subject, I would limit it to Chrome devtools and focus on how to get started 

resources
I will link them later

Scheduling
Hopefully before 2019 ends, mid to end Dec if possible 😅 (I'm targetting 20th Dec?) 
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by: 6th Dec
- Needs dry run: sure

**Comment by wgao19** [comment]
cool! off my mind: since we have plenty of time, would you like to have a brief chat to go over materials you have on hand for some brainstorm / organization into talk outline? we can do that late nov or early dec, depending on your pace

**Comment by heyjiawei** [comment]
sure, I'll let you know :)

**Comment by heyjiawei** [comment]
Hey @wgao19 I don't know how to add emoji to the issue tracker. After googling, :seedling: doesn't appear. Do you copy and paste the emoji into the issue tracker?

**Comment by wgao19** [comment]
lol magic, although i notice u used an elephant before which is also cute :P

sorry seeing a lot of repeating purple ghost emojis recently

**Comment by wgao19** [comment]
Thank you for being the first speaker live streamed, and more so for preparing the talk!
