### ISSUE TITLE
🎙 #learnInPublic Show-and-Tell

### ISSUE THREAD

**Issue by wgao19** [Shopee/shopee-react-knowledgeable#164]
wat dis
---
would like to poke our learners in public to show-and-tell things you learn, your experience, and fun stories etc., we got 35 minutes, so number of minutes we each got ⚡️ is 35 divided by number of us speaking

- [x] @Tzyinc 
- [ ] @t1ger-0527 
- [ ] @kenrick95 
- [x] @tanhauhau 
- [x] @heyjiawei
- [ ] @Matherunner 
- [x] @SmokinClove
- [ ] @wgao19
- [ ] ...you?

logistics
---
- date: dec 13
- plz confirm ur spot **by replying your outline**

links to videos
---
- @Tzyinc **5 Months into #learnInPublic** / pecha kucha  
  https://youtu.be/0TUP5qEBYhQ?t=23
- @tanhauhau  
  https://youtu.be/NSUa1124ahs
- @heyjiawei  
  https://youtu.be/1V72ooyE8PE
- @SmokinClove - #learnInPublic Demon Angel and Jellyfish   
  https://youtu.be/1V72ooyE8PE

**Comment by SmokinClove** [comment]
My rough outline:
1. How i started to try Learning in Public (and Why i continued to try Learning in Public)
2. The internal struggles of Learning in Public, from my personal experience
3. What Learning in Public ultimately means to me

Talk title: it's (still) a secret <3

**Comment by tanhauhau** [comment]
My rough outline (kinda similar to @SmokinClove):
1. Why and how I started to try Learning in Public
1. How is it different from learning in private?
1. What have I learned about so far?
1. If time permits, probably what is the goal I set for myself next year?

**Comment by heyjiawei** [comment]
To be honest I don't really get what we are suppose to talk about but judging from the above speakers outline it seems like we ought to talk about our experience with learning in public so,

My rough outline: 
1. How I was learning previously and how effective it was
2. Has learning in public really helped? (I will try to keep this light-hearted to respect our guest but I do want to share some honest thoughts here. Will run this through with you first :) )
3. Fears and future goals, milestones

**Comment by wgao19** [comment]
Great. Thank you @SmokinClove @tanhauhau @heyjiawei for your proposals! Let's close this speaker line-up as is now and you each will have 11 2/3 minutes.

While we have been pretty lenient about time (we say time is x mins but we don't really run a timer, or allow people to keep talking after the timer runs off), we gonna cut it sharp when timer runs up this time. Please run your talk by yourself to make sure you don't get cut off at bad time (or drop your best jokes in the beginning).

**Comment by Tzyinc** [comment]
oops can i still join?

**Comment by Tzyinc** [comment]
rough outline

1. why I attempt learning in public
2. why (in my opinion) tangible results from learning in public don't matter
3. what I have done so far
4. personal learning in public goals

**Comment by wgao19** [comment]
oops, no, too late

**Comment by wgao19** [comment]
so @heyjiawei and @tanhauhau decided to spare @Tzyinc some minutes, current schedule:
- @SmokinClove 11 mins 40 secs
- @tanhauhau 10 mins 40 secs
- @heyjiawei 6 mins
- @Tzyinc 6 mins 40 secs (pecha kucha)

if you've run talk and have more accurate approximation, can update here
