### ISSUE TITLE
☕️  Code splitting 101

### ISSUE THREAD

**Issue by nah611** [Shopee/shopee-react-knowledgeable#165]
speaker
---
An Ha

intro
---
Overview of code splitting and how it's handled during compilation and runtime by Webpack.
Pros/cons and how can we utilise code splitting for better UX.

resources
---
https://github.com/webpack/webpack
https://webpack.js.org/guides/code-splitting/
https://webpack.js.org/api/module-methods/

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ <30 mins
- Ready by: 13 Dec
- Needs dry run: sure

**Comment by wgao19** [comment]
Would like to poke you to pick a different emoji, thanks.

**Comment by nah611** [comment]
sure, updated

**Comment by wgao19** [comment]
Thank you for the talk!

Here's [link to the video](https://drive.google.com/file/d/12LzG5xIMDUUI5gfoovfVdMnRD7MHMbG9/view?usp=sharing) for internal sharing, request access with your work email if needed.
