### ISSUE TITLE
🌉 Recap on CDS 2019

### ISSUE THREAD

**Issue by t1ger-0527** [Shopee/shopee-react-knowledgeable#167]
speaker
---
@t1ger-0527 

intro
---
Highlights during the conference.

resources
---

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: Dec 6
- Needs dry run: 🤔

**Comment by wgao19** [comment]
coooooooolio

**Comment by wgao19** [comment]
Hi @t1ger-0527 could you please pick a different emoji?
