### ISSUE TITLE
🐹 How to implement ReactDOMServer's renderToString() function?

### ISSUE THREAD

**Issue by Sueweetie3** [Shopee/shopee-react-knowledgeable#169]
speaker
Zhang Xue

intro
1. introduction about SSR, including differences between SSR and CSR, pros and cons of SSR.
2. [main part]how does renderToString() work? What does react do to prevent XSS?
3. how do SSR frameworks fetch data beforehand?

resources
---

- slides
https://docs.google.com/presentation/d/1mg9Ryq9uDRV_RIbwOlykpmxUGQA72XV3PLefjAwFG98/edit#slide=id.gcb9a0b074_1_0
- more links
https://dev.to/sunnysingh/the-benefits-and-origins-of-server-side-rendering-4doh
https://overreacted.io/react-as-a-ui-runtime/
https://prismic.io/blog/how-gatsby-and-nextjs-really-work
...

Scheduling
---
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by: Dec 16
- Needs dry run: sure

**Comment by wgao19** [comment]
Hi @Sueweetie3 thank you for proposing this talk! Since you mentioned you'd like dry run this talk, will Dec 20 be a good date for the dry run?  

Meanwhile, depending on how many people will go on leave during this holiday season, I have in mind to put your talk on either Jan 3 or Jan 10. Is this OK with you?

Also, do you mind changing an emoji?

**Comment by Sueweetie3** [comment]
Ok~
Thank you ~

Wei Gao <notifications@github.com>于2019年12月7日 周六下午11:49写道：

**Comment by wgao19** [comment]
Hi @Sueweetie3 would like to have your help updating a title and an emoji for this :) thanks!

**Comment by Sueweetie3** [comment]
@wgao19  sure, have updated

**Comment by wgao19** [comment]
@Sueweetie3 thanks!

**Comment by wgao19** [comment]
[link to video](https://drive.google.com/open?id=12fkncDRDPWBe23LkKKAr1P3eTFGYhuAD) for internal sharing (request access if needed)
