### ISSUE TITLE
React Knowledgeable #58 - 🎰 PowerPoint Karaoke 🎲 - Dec 27, 2019

### ISSUE THREAD

**Issue by wgao19** [Shopee/shopee-react-knowledgeable#170]
# React Knowledgeable Week 58

🗓 Date: 18:00, Friday,

🦄 Host:

PowerPoint Karaoke for Xmas? @KenLSM WDYT?
- [X] @tanhauhau
- [X] @maxis1718 
- [X] @Matherunner
- [X] @usrbowe
- [X] @qihaomah
- [X] @Ridwansameer
- [X] @nutstick
- [X] @KevinHu2014
- [X] @ynov
- [ ] maybe you?
<details>
 <summary>Checklist</summary>

- [x] submitted request for cafe booking [link to edit](https://docs.google.com/forms/d/e/1FAIpQLScwj8SVQDUypQBbujFsHbeawwatb4j53aJ61pPLVwElmqLTrQ/viewform?edit2=2_ABaOnucwVN1AaKyuR_KEjkwhahlfECm7HTkU-FIAunk5LLssTClEaPLd4AlsBOykkWpQw7g)
- [x] venue confirmed & additional booking cancelled

</details>

**Comment by usrbowe** [comment]
I'm in -> @usrbowe 🙏

**Comment by qihaomah** [comment]
I'm Qi Hao

**Comment by Ridwansameer** [comment]
Im in :)

**Comment by KevinHu2014** [comment]
I'm in :)

**Comment by ynov** [comment]
I'm in!

**Comment by wgao19** [comment]
amazing performances, thank you all!
