### ISSUE TITLE
React Knowledgeable #59 - 👩🏻‍🏫 Two people are lying 👨🏻‍🏫 - Jan 3

### ISSUE THREAD

**Issue by KenLSM** [Shopee/shopee-react-knowledgeable#172]
# React Knowledgeable Week 59

🗓 Date: 18:00, Friday,

🦄 Host: @KenLSM 

Let's play "Two of these people are lying" for New Year? @wgao19 
- [X] @tanhauhau 
- [X] @Tzyinc
- [X] @maxis1718 
- [X] @Matherunner
- [X] @usrbowe
- [X] @qihaomah
- [X] @Ridwansameer
- [X] ~~@nutstick~~
- [X] @KevinHu2014
- [X] @heyjiawei
- [x] @kenrick95 
- [x] @t1ger-0527 
- [x] @AdrielLimanthie
- [x] @aaron-maslim
- [x] @ynov
- [x] @gejimayu
- [ ] maybe you?

#### Rules of the game
- 3-5 people participate in the game
- it's an improvisational game

#### Before each session
- each participant will be given one Wikipedia article of interest

#### During each session
- the host will choose one of the articles
- the host will ask questions to participants to facilitate discussion of the topic
- as n-1 participants don't know anything about the topic, they will have to converse/bluff/improvise with the host as if their topic was chosen

#### After each session
- audiences will be voting to determine whose topic was chosen

### Reference
[Matt and Tom](https://www.youtube.com/watch?v=3UAOs9B9UH8) and friends playing the game

<details>
 <summary>Checklist</summary>
- [ ] submitted request for cafe booking
- [ ] venue confirmed & additional booking cancelled

</details>

**Comment by heyjiawei** [comment]
🙋 count me in

**Comment by JennieJi** [comment]
🤔 what's this

**Comment by KenLSM** [comment]
@JennieJi added more context! LMK if I'm missing some explanation.

**Comment by t1ger-0527** [comment]
Great game! Thanks for hosting this one @KenLSM 👍

**Comment by wgao19** [comment]
Thank you @KenLSM !!
