### ISSUE TITLE
🤡 "CSS"

### ISSUE THREAD

**Issue by kenrick95** [Shopee/shopee-react-knowledgeable#176]
speaker
---
@kenrick95 

intro
---

@wgao19 successfully "blackmail" me into giving a talk so that my streak of "14-week interval" between my talks wasn't broken even though a more thorough investigation breaks this claim 🕵

Anyway, I wanna share about ["CSS"](https://en.wikipedia.org/wiki/Cross-site_scripting), even though no one uses that acronym; this will have lots of demos, that's why it's challenging to prepare.

resources
---

- Slides here: https://docs.google.com/presentation/d/1h7k9OzIM7Ro21jsMy9PP9H2vuBAF_ew5Dag8KooeZts/
- Demo repo: https://github.com/kenrick95/xssdemos
- Video (live streamed!): https://www.youtube.com/watch?v=RiCMECA2RUI

Scheduling
---
- Estimated duration: ⚡️ 7 mins / 🧙🏻‍♂️ 30 mins. Don't know yet. still preparing.
- Ready by: 🤷‍♀️ targeting for RK Week # 64
- Needs dry run: Yes, don't know yet

**Comment by wgao19** [comment]
Hello @kenrick95 RK week 64 is scheduled to Feb 21, and this date should be rather reliable now. I'm wondering -- would you like to pick a dry run date? I think Feb 14 should be good since Feb 7 got company event. Jan 31 also open.

**Comment by kenrick95** [comment]
14 Feb please, thanks

**Comment by wgao19** [comment]
thank you! updated slides / links in the video also :)

and, you can now see the video from our home page as well, in the "passed live streams" section
