### ISSUE TITLE
🔒 Cryptology for Web Developers

### ISSUE THREAD

**Issue by t1ger-0527** [Shopee/shopee-react-knowledgeable#180]
speaker
---
@t1ger-0527 

intro
---
When working on an ad-hoc anti-fraud projects on order side, I learned a lot about Cryptology. So I plan to share the knowledge.
This talk will be about some Cryptology basics for Web Developers to know, so you don't look like an idiot when you talk about Cryptology or implement features using `crypto-js`. (That's what I did)
Outline:
- Signing or Encryption?
- How does `HTTPS` work behind the scene? (Will involve TLS/SSL)
- Block Cipher basics (what is `AES` and how to use it), including:
  - What is `key`, `block`and `iv`?
  - Common practices when you try to encrypt something. (very practical, will be my main focus)
- Cryptology history (Can trace back to 700 B.C.) I read some books about this when I was a kid. Will decide if we add in or not depends on timing. Low priority.
  - I wish to at least tell the [illegal shirt story](https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States)

resources
---
Some documentation and my practice experience.

Scheduling
---
- Estimated duration:  🧙🏻‍♂️🧙🏻‍♂️ 45 mins
- Ready by: Feb 16th (I will take 3-weeks leave during CNY)
- Needs dry run: Yes please!

**Comment by wgao19** [comment]
so cool! poking you tmr to schedule our dry run :)

**Comment by wgao19** [comment]
Thank you for the talk!
