### ISSUE TITLE
🤖 find what code is affected from your change

### ISSUE THREAD

**Issue by JennieJi** [Shopee/shopee-react-knowledgeable#182]
speaker
---
@JennieJi 

intro
---
Talking about what I am trying to do in repo https://github.com/JennieJi/ast-lab with AST:
- finding relationships
- affected changes
- automated cleanups
and other ideas.

resources
---

Scheduling
---
- Estimated duration: ⚡️ 7 mins / 🧙🏻‍♂️ 30 mins (not sure yet, will update once draft is ready)
- Ready by: 6/15 March
- Needs dry run: yes

**Comment by tanhauhau** [comment]
looking forward 👍

**Comment by wgao19** [comment]
cool, can change an emoji plz

**Comment by JennieJi** [comment]
@wgao19 thanks for the suggestions and I decided to reform the whole talk to be a form of my journey to make ast-lab repo, some code key points and problems met, probably will take 30 mins.

Do we still have dry run this week?

**Comment by wgao19** [comment]
@JennieJi cool, the dry run hour for this Friday is open if you need it, or we can also do a less formal walk through of the content

**Comment by JennieJi** [comment]
Thank you so much @wgao19 less formal shall do ORZ

**Comment by JennieJi** [comment]
https://docs.google.com/presentation/d/1FeAAMjCLJvHQxulb76tSR4vI5wxOqlu1DSCsJZg8G2o/edit?usp=drivesdk
slides here

**Comment by wgao19** [comment]
cool, thank you @JennieJi for the talk! will update video url once we done the editing

**Comment by wgao19** [comment]
Hey @JennieJi the video to only your talk (without the RK nonsense) is here: https://youtu.be/_tNeRsYf8ks
