### ISSUE TITLE
Frööt Lööps 🔁

### ISSUE THREAD

**Issue by Tzyinc** [Shopee/shopee-react-knowledgeable#186]
speaker
---
Tenzy

intro
---
We use loops in programming all the time, but when should we use map, foreach, reduce and why are we so resistant to use simple for loops?

resources
---
`All code using array.reduce should be rewritten without array.reduce`
https://twitter.com/jaffathecake/status/1213077702300852224
`loops comparison`
https://www.blog.duomly.com/for-loop-while-loop-do-while-loop-and-other-javascript-loops-comparison-and-performance/
`another loops comparison`
https://towardsdatascience.com/javascript-performance-test-for-vs-for-each-vs-map-reduce-filter-find-32c1113f19d7

- slides https://slides.com/tzyinc/deck

Scheduling
---
- Estimated duration: ⚡️ 7 mins / 🧙🏻‍♂️ 30 mins (not sure yet)
- Ready by: 17 april
- Needs dry run: yes

**Comment by wgao19** [comment]
thanks for disssss :)
