### ISSUE TITLE
RK #68 - "Read Knowledgeable" Special Edition

### ISSUE THREAD

**Issue by wgao19** [Shopee/shopee-react-knowledgeable#189]
## React Knowledgeable Week 68

🗓 Date: 18:00, Friday, Mar 27, 2020
🦄 Host: @wgao19 @KenLSM 
🗺 Location: Zoom or YouTube

@KenLSM joins @wgao19 to lead a chat with everyone on reading.

- do you read?
- what do you read?
- do you get peer pressure for (not) reading?
- any interesting books you want everybody to read?

Let's do a group discussion on reading. Bring your books and curiosities (to other people's reads).

We don't even need to change twitter handle -- reknowledgeable still works!

**Comment by wgao19** [comment]
depending on technical details, we'll decide whether we'll con-call with zoom or stream YouTube later this week

**Comment by sw-yx** [comment]
zoom!

**Comment by wgao19** [comment]
hey @sw-yx yup we are using zoom (and youtube)! join us this week :)

**Comment by wgao19** [comment]
recap and a few useful links

do you read
---
**chenchen's story**  
reads to learn things more systematically, i.e., carpenting, cooking

**tenzy's story**  
annual reading challenge 1 book

**wei's story**  
reads from childhood, didn't read much in college, resumes reading after starting to work

**ken's story**  
finds reading for free time, reads for pleasure

what do you read
---
we haven't covered this too much, have we?

where to get books
---
- library
  - national library
  - [overdrive](https://www.overdrive.com/) / [nlb overdrive](https://nlb.overdrive.com/) allows you to borrow ebooks from library
- online bookstore
  - [abebooks](https://www.abebooks.com/) used books with decent care and categorization according to conditions
  - [book depository](https://www.bookdepository.com/) decent prices, ships from UK so a bit slow
- electronic readers
  - kindle
  - kobo
  - 微信读书 mainly Chinese books, has apps for kindle
- read in bookstore

how to find next reads
---
- goodreads
  - [kenrick](https://www.goodreads.com/user/show/58461167-kenrick)
  - [jennie](https://www.goodreads.com/user/show/88084938-jennie-ji)
  - [huijing](https://www.goodreads.com/user/show/7679266-hui-jing)
  - [chenchen's douban](https://book.douban.com/people/pedi/) so outdated, i'm disappointed :(
  - [ridwan](https://www.goodreads.com/user/show/25957787-ridwan-sameer)
  - [tenzy](https://www.goodreads.com/user/show/77555179-ten-zhi)
- podcasts
- finds books about figures who all of a sudden become rich
- [blinkist](https://www.blinkist.com/) additional recommendation by mohsen
- [bpluspodcast](https://bpluspodcast.com/) additional reference by mohsen, if you read _persian_

recommend me a book
---
- [history of rome (podcast)](https://podcasts.google.com/?feed=aHR0cDovL2hpc3RvcnlvZnJvbWUubGlic3luLmNvbS9yc3M) from chenchen
- [1453](https://www.goodreads.com/book/show/227354.1453) from wei
- [How To: Absurd Scientific Advice for Common Real-World Problems](https://www.goodreads.com/book/show/42086897-how-to) from kenrick
- [point us to a book](https://github.com/wgao19/point-us-to-a-book) additional reference by wei, a twitter thread started by dan abramov

**Comment by Tzyinc** [comment]
Re: what do you read: ken was talking about `12 rules to life` and tiger mentioned `song of ice and fire`, chenchen mentioned the woodworking one i cant remember, and also some cooking book, kenrick mentioned the colors book that you can borrow from his table

**Comment by wgao19** [comment]
thanks @Tzyinc!

**Comment by sw-yx** [comment]
i'm sorry i slept thru this call :( fwiw i was reading thru an early copy of https://www.dynamodbbook.com/ and finished skimming it yesterday! i love reading technical books cover to cover.

**Comment by wgao19** [comment]
Thanks for the recommendation @sw-yx! And you'll have many more Fridays to join :)
