### ISSUE TITLE
📝 Coding HTML Email

### ISSUE THREAD

**Issue by aaron-maslim** [Shopee/shopee-react-knowledgeable#191]
speaker
---
Aaron

intro
---
Email is one of the most important form of communication nowadays, thus it is important to make sure the recipient of your emails see what you want them to see.

resources
---

Scheduling
---
- Estimated duration:  🧙🏻‍♂️ 30 mins
- Ready by: 2 April
- Needs dry run: Yes

**Comment by wgao19** [comment]
Thank you for this amazing talk! Here's the link to the video: https://youtu.be/X5bcXfkW__U

Also, waiting for @KenLSM to pick a thumbnail with a taste :)

**Comment by aaron-maslim** [comment]
Thank you for organising the talk @wgao19 !
