### ISSUE TITLE
🌍 your i18n should use StaticQuery

### ISSUE THREAD

**Issue by nutstick** [Shopee/shopee-react-knowledgeable#193]
speaker
---
@nutstick

intro
---
Propose my idea on how we should implement i18n inspire by @gatsbyjs (which is used @graphql)

resources
---
- [video](https://www.youtube.com/watch?v=0n7qMocglHw&t=5794s)

**Comment by wgao19** [comment]
🎉 thank you!

**Comment by wgao19** [comment]
@nutstick you da best 💜

[here's the link to the video](https://www.youtube.com/watch?v=0n7qMocglHw&t=5794s)
