### ISSUE TITLE
🌐 i18n - A short story

### ISSUE THREAD

**Issue by mohsenshafiei** [Shopee/shopee-react-knowledgeable#194]
speaker
---
Mohsen

intro
---
Review i18n approaches and presenting a new approach to add i18n

resources
---

Scheduling
---
- Estimated duration: ⚡️ 🧙🏻‍♂️ 30 mins
- Ready by: 17 Apr
- Needs dry run: Yes

**Comment by wgao19** [comment]
Hey @mohsenshafiei here's the [link to the talk](https://www.youtube.com/watch?v=0n7qMocglHw&t=1067s), you can view it with the live chat now 🤣 and I will pass you the sticker next time we in office 😅

Thanks again for the talk, it was really really great. And it let me in to look into i18n as well so it means so much more to me now xD
