### ISSUE TITLE
🤔 To control, or not to control?

### ISSUE THREAD

**Issue by LookRain** [Shopee/shopee-react-knowledgeable#195]
speaker
---
Lu Yu (Louis) @LookRain

intro
---
Controlled forms in React are feature-rich, but comes with its performance issues. Uncontrolled forms are lightweight, but doesn't seem to tick all the boxes when it comes to features. Can we have the best of both worlds?🤔

resources
---

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by:  7th May
- Needs dry run: Not sure yet

**Comment by wgao19** [comment]
Hey @LookRain how's this going now?

**Comment by wgao19** [comment]
Video: https://youtu.be/X51J2KyPxL4

Thanks again for this sharing!
