### ISSUE TITLE
🍱 Localisation without pain

### ISSUE THREAD

**Issue by yishus** [Shopee/shopee-react-knowledgeable#197]
haha sorry I just anyhow write one title ☝️ 

speaker
---
@imouto1994

intro
---
Overview of localisation on Carousell web

resources
---

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: 17 Apr
- Needs dry run:

**Comment by wgao19** [comment]
hey @imouto1994 @yishus [here's the link to the video of @imouto1994's talk](https://www.youtube.com/watch?v=0n7qMocglHw&t=3278s) :)

thanks again for being part of our 70th event, let's do this more often in the future!!
