### ISSUE TITLE
🔌 Supercharge your localisation with LocalizedNode

### ISSUE THREAD

**Issue by yishus** [Shopee/shopee-react-knowledgeable#198]
speaker
---
@ayao1917

intro
---
What if you need more than just strings?

resources
---

Scheduling
---
- Estimated duration: ⚡️ 7 mins
- Ready by: 17 Apr
- Needs dry run:

**Comment by wgao19** [comment]
hey @ayao1917 [here's the link to the video of your talk](https://www.youtube.com/watch?v=0n7qMocglHw&t=4931s)

thanks for showing us this implementation! aaand really hope to see you again in the upcoming RK events :)
