### ISSUE TITLE
⛵️ the Raft consensus algorithm

### ISSUE THREAD

**Issue by wanghaoPolar** [Shopee/shopee-react-knowledgeable#199]
speaker
---
@wanghao

intro
---
modern day web service rely on distributed system to provide linear-scalable high performance or high availability.

after Paxos's decades of predominance, Raft came out in 2013 as a more understandable replacement.

now Raft has became one of the most important consensus algorithm, acting as the foundation of other popular projects like etcd, TiKV, Consul, etc.

in this sharing, I will
1. introduce what is consensus algorithm, and why is it important
2. explain how Raft works, and how to implement a basic version of Raft
3. explain the principle of how to build a simple KV storage software on top of Raft

resources
---

the official site of Raft: https://raft.github.io , you can find an interactive demo to get a general idea of Raft

Scheduling
---
- Estimated duration: 🧙🏻‍♂️ 30 mins
- Ready by: 11th May
- Needs dry run: Yes

**Comment by wgao19** [comment]
👍 up, and, 199 is a good number :)

**Comment by Tzyinc** [comment]
wow first talk? :clap:

**Comment by wgao19** [comment]
hey @wanghaoPolar do u mind sharing the slides also?

**Comment by wanghaoPolar** [comment]
here is the slide~: https://docs.google.com/presentation/d/12OX8NU0O3tVuRekA1oXefMnqvXQqnJffMSFhOPuTKBQ/edit?usp=sharing

**Comment by wgao19** [comment]
Video: https://youtu.be/cjkH-z7HvzU (will be public on Wed)
Thank you again for the great sharing!
