### ISSUE TITLE
🌌 Fun Facts of Nebula: How to interact with the children of your component?

### ISSUE THREAD

**Issue by sjDu** [Shopee/shopee-react-knowledgeable#203]
speaker
---
James Du

intro
---
Share some thoughts during the implementation of Nebula. This time we are going to introduce how we detect a child component in our component with the pattern we found.

resources
---

- slides: https://slides.com/jamesdu/interact-with-children/live

Scheduling
---
- Estimated duration: ⚡️ 15 mins 
- Ready by: 4th May
- Needs dry run: No

**Comment by wgao19** [comment]
cooool here's the finalized video: https://youtu.be/O1JCHV7xonQ

thanks @KenLSM again for the amazing work on thumbnails 🙈 and thank you @sjDu for the talk! hope to hear from u again soon
