### ISSUE TITLE
⛰️ Overview of WebRTC

### ISSUE THREAD

**Issue by Matherunner** [Shopee/shopee-react-knowledgeable#70]
Speaker
---
@Matherunner 

Intro
---

I might be able to talk a bit about WebRTC and some of the fundamentals. I'll include some demos. The talk will cover the web APIs and some networking stuff.

Ready by
---
March? April?

**Comment by wgao19** [comment]
Hi @Matherunner any updates for this talk?

**Comment by Matherunner** [comment]
This one won't come so soon 😅 Still working on the demo

**Comment by wgao19** [comment]
No worries! Curious about your demo, though :P Hoping to see it soon!

**Comment by wgao19** [comment]
Hi @Matherunner  looking forward to this talk now, how's it going? 👀

**Comment by Matherunner** [comment]
Finally got a breakthrough, I fixed a longstanding issue in the demo.

**Comment by wgao19** [comment]
Sounds great! Would you like to develop it into a talk recently?

**Comment by Matherunner** [comment]
Yeah I'm working on the slides now. I also tested the demo on the office network, and it seems to work.

**Comment by wgao19** [comment]
Hey @Matherunner shall i schedule this talk for aug 16? if you need dry run, july 26 and aug 2 are both open

**Comment by Matherunner** [comment]
OK I think Aug 2 would be good for my dry run.

**Comment by wgao19** [comment]
@Matherunner scheduled this in for Aug 23 on #128

**Comment by KenLSM** [comment]
@Matherunner Thanks for your networking masterclass today! Could you also upload your slides so that I can close this issue?

**Comment by wgao19** [comment]
[slides](https://drive.google.com/open?id=1ckqIwNrbCrbNFfOOdqM7AXtIxo1ISd_hyZa1LAHFFnM)
