### ISSUE TITLE
⛰️ MLS-MPM Solver in detail.

### ISSUE THREAD

**Issue by t1ger-0527** [Shopee/shopee-react-knowledgeable#99]
Speaker
---

@t1ger-0527 

Intro
---

Understanding [this algorithm](https://github.com/yuanming-hu/taichi_mpm) and maybe [this paper](https://www.seas.upenn.edu/~cffjiang/research/mlsmpm/hu2018mlsmpm.pdf)

Ready by
---

Not sure. Still learning it.

**Comment by wgao19** [comment]
Hi @t1ger-0527  any updates on this talk?

**Comment by t1ger-0527** [comment]
Close cause no progress on this one 🙈 
Maybe will revisit later.

**Comment by wgao19** [comment]
sure :)
